ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.ApplicationKt.module
jwt:
  issuer: "ktor-events"
  audience: "ktor-events-users"
  realm: "events-api"
  secret: "super-secret-for-dev"
database:
  url: "jdbc:postgresql://localhost:5432/events"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "postgres"
